verbose: false
go:
  cgo: false
repository:
  path: github.com/orange-cloudfoundry/mdproxy4cs
build:
  flags: -a -tags 'netgo static_build'
  ldflags: |
    -X {{repoPath}}/version.Version={{.Version}}
    -X {{repoPath}}/version.Revision={{.Revision}}
    -X {{repoPath}}/version.Branch={{.Branch}}
    -X {{repoPath}}/version.BuildUser=psycofdj@{{host}}
    -X {{repoPath}}/version.BuildDate={{date "20060102-15:04:05"}}
tarball:
  files:
    - LICENSE
    - assets/mdproxy4cs.service
    - assets/pre-start.sh
crossbuild:
  platforms:
    - linux/amd64

